spring.application.name=gtog
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=gtog_dev
management.endpoint.health.show-details=always
management.health.mongodb.enabled=false
spring.devtools.restart.enabled=false
spring.jmx.enabled=false
management.endpoints.jmx.exposure.exclude=*
logging.level.sun.rmi=OFF